import { type IRegion } from './Region';

export interface IRegionScopeData {
  [index: string]: IRegion

  'RU-AD': IRegion
  'RU-AL': IRegion
  'RU-BA': IRegion
  'RU-BU': IRegion
  'RU-DA': IRegion
  'RU-IN': IRegion
  'RU-KB': IRegion
  'RU-KL': IRegion
  'RU-KC': IRegion
  'RU-KR': IRegion
  'RU-KO': IRegion
  'UA-43': IRegion
  'RU-ME': IRegion
  'RU-MO': IRegion
  'RU-SA': IRegion
  'RU-SE': IRegion
  'RU-TA': IRegion
  'RU-TY': IRegion
  'RU-UD': IRegion
  'RU-KK': IRegion
  'RU-CE': IRegion
  'RU-CU': IRegion
  'RU-ALT': IRegion
  'RU-ZAB': IRegion
  'RU-KAM': IRegion
  'RU-KDA': IRegion
  'RU-KYA': IRegion
  'RU-PER': IRegion
  'RU-PRI': IRegion
  'RU-STA': IRegion
  'RU-KHA': IRegion
  'RU-AMU': IRegion
  'RU-ARK': IRegion
  'RU-AST': IRegion
  'RU-BEL': IRegion
  'RU-BRY': IRegion
  'RU-VLA': IRegion
  'RU-VGG': IRegion
  'RU-VLG': IRegion
  'RU-VOR': IRegion
  'RU-IVA': IRegion
  'RU-IRK': IRegion
  'RU-KGD': IRegion
  'RU-KLU': IRegion
  'RU-KEM': IRegion
  'RU-KIR': IRegion
  'RU-KOS': IRegion
  'RU-KGN': IRegion
  'RU-KRS': IRegion
  'RU-LEN': IRegion
  'RU-LIP': IRegion
  'RU-MAG': IRegion
  'RU-MOS': IRegion
  'RU-MUR': IRegion
  'RU-NIZ': IRegion
  'RU-NGR': IRegion
  'RU-NVS': IRegion
  'RU-OMS': IRegion
  'RU-ORE': IRegion
  'RU-ORL': IRegion
  'RU-PNZ': IRegion
  'RU-PSK': IRegion
  'RU-ROS': IRegion
  'RU-RYA': IRegion
  'RU-SAM': IRegion
  'RU-SAR': IRegion
  'RU-SAK': IRegion
  'RU-SVE': IRegion
  'RU-SMO': IRegion
  'RU-TAM': IRegion
  'RU-TVE': IRegion
  'RU-TOM': IRegion
  'RU-TUL': IRegion
  'RU-TYU': IRegion
  'RU-ULY': IRegion
  'RU-CHE': IRegion
  'RU-YAR': IRegion
  'RU-MOW': IRegion
  'RU-SPE': IRegion
  'UA-40': IRegion
  'RU-YEV': IRegion
  'RU-NEN': IRegion
  'RU-KHM': IRegion
  'RU-CHU': IRegion
  'RU-YAN': IRegion
  'KZ-BAY': IRegion
}
