export { AllRegion } from './AllRegion';
export {AnomalyTableData} from './AnomalyTableData'
export { ChartId } from './ChartId';
export { Comparison } from './Comparison';
export { Lab } from './Lab';
export { LabNameRU } from './LabNameRU';
export { Parameter } from './Parameter';
export { IParameterDetails } from './ParameterDetails';
export { PlotData } from './PlotData';
export { ProcessorConfiguration  } from './ProcessorConfiguration';
export { ProInflammatoryIndicators } from './ProInflammatoryIndicatorsTableData';
export { Region } from './Region';
export { RegionIsoCode } from './RegionIsoCode';
export { RegionMap, DataWhen} from './RegionMap';
export { RegionNameRu } from './RegionNameRu';
export {LayoutDirection } from './resultFlow';
export { PhrasesResponse, SendPhraseParams} from './WordStat';
export { IChartRequestParams} from './сhartRequestParams';
export {Direction} from './Direction';
export {Timeline} from './Timeline';
export {TimelineProps} from './TimelineProps';
