pnpm add \
    @dagrejs/dagre \
    @deck.gl/core \
    @deck.gl/layers \
    @deck.gl/react \
    @emotion/react \
    @fontsource/geologica \
    @mui/icons-material \
    @mui/lab \
    @mui/x-data-grid \
    @mui/x-date-pickers \
    @reduxjs/toolkit \
    @tanstack/react-table \
    @tanstack/table-core \
    @turf/bbox \
    @uiw/react-split \
    apexcharts \
    core-js \
    d3 \
    dayjs \
    dotenv \
    final-form \
    final-form-focus \
    final-form-set-field-data \
    glob \
    idb \
    lodash \
    mapbox-gl \
    mapbox-gl-utils \
    mui-rff \
    notistack \
    plotly.js \
    re-resizable \
    react-apexcharts \
    react-final-form \
    react-icons \
    react-intersection-observer \
    react-map-gl \
    react-plotly.js \
    react-redux \
    react-reflex \
    react-router-dom \
    react-spring \
    react-stack-cards \
    reactflow \
    redux \
    styled-components \
    tinycolor2 \
    utility-types \
    uuid \
    y-prosemirror \
    yup
